Make buttons look nicer ...
ViktorRubenko/FastScripts pull request #8
Opened 2022-01-18 09:25 UTC by Mark2Mark

... and use non-deprecated bezel API, smaller text to trunkate longer script names less early.

2022-01-18 10:42 UTC, ViktorRubenko commented on FastScripts.glyphsPalette/Contents/Resources/plugin.py
> +    NSBezelStyleRecessed,
Doesn't work for the 2nd version.
Maybe add a condition to use NSShadowlessSquareBezelStyle/NSBezelStyleRecessed for 2/3?

2022-01-18 10:50 UTC, ViktorRubenko requested changes

2022-01-18 10:50 UTC, ViktorRubenko commented on FastScripts.glyphsPalette/Contents/Resources/plugin.py
> +    NSBezelStyleRecessed,
Doesn't work for the 2nd version.
Maybe add a condition to use NSShadowlessSquareBezelStyle/NSBezelStyleRecessed for 2/3?

2022-01-18 16:48 UTC, Mark2Mark commented
I made a second commit, maybe that works? For me it now works in G2 as before, and in G3 with the more sleeker buttons.

2022-01-19 14:54 UTC, ViktorRubenko approved these changes

2022-01-19 14:54 UTC, merged

2022-01-19 14:57 UTC, Mark2Mark commented
Thanks a lot. Hope you like it :)

2022-01-19 17:58 UTC, ViktorRubenko commented
@Mark2Mark I'm glad for any help, thanks :)

2022-01-20 12:51 UTC, Mark2Mark commented
Ill see if I can pus another fix, as it looks nice here on Big Sur and Monterey, but a bit dark on Catalina …

2022-01-20 14:07 UTC, ViktorRubenko commented
I'll try to check tomorrow how it looks on Catalina